apiVersion: v1
kind: Pod
metadata:
  name: busybox
  namespace: todoapp
spec:
  containers:
  - name: busybox-container
    image: ikulyk404/busyboxplus:curl
    command: ["sh", "-c", "while true; do echo 'Running'; sleep 30; done"]
